version: "3.4"
services:
  beacon_node:
    build:
      context: .
      dockerfile: ./lodestar/Dockerfile
    network_mode: host
    restart: always
    volumes:
      - beacon_node:/beacondata
      - logs:/logs
    ports:
      - "9596:9596" # REST API port
    command: >
      beacon
        --rootDir=/beacondata
        --paramsFile=/config.yaml
        --genesisStateFile=/genesis.ssz
        --network.discv5.bootEnrs="enr:-Iq4QKuNB_wHmWon7hv5HntHiSsyE1a6cUTK1aT7xDSU_hNTLW3R4mowUboCsqYoh1kN9v3ZoSu_WuvW9Aw0tQ0Dxv6GAXxQ7Nv5gmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
        --network.connectToDiscv5Bootnodes 
        --network.discv5.enabled=true
        --eth1.enabled=true
        --api.rest.port=9596
        --eth1.disableEth1DepositDataTracker=true
        --eth1.providerUrls=http://127.0.0.1:8545
        --execution.urls=http://127.0.0.1:8545
        --api.rest.enabled=true
        --api.rest.host=0.0.0.0
        --api.rest.api="*"
        --logLevel=info
        --logLevelFile=debug
        --logFile=/logs/beacon.log
        --logRotate
        --logMaxFiles=5

    # NodeJS applications have a default memory limit of 2.5GB.
    # This limit is bit tight for a Prater node, it is recommended to raise the limit
    # since memory may spike during certain network conditions.
    environment:
      NODE_OPTIONS: --max_old_space_size=6144
      LODESTAR_PRESET: minimal

  geth:
    build: ./geth
    network_mode: host
    volumes:
      - geth:/eth1Data
    ports:
      - "30303:30303"
      - "8545:8545"

volumes:
  beacon_node:
  logs:
  geth:

